### PR TITLE
Add affiliation or membership to project members

### PR DESCRIPTION
**Pull request by beutlich**

### CODE REVIEW

**Comment by tobolar** [comment]
@beutlich Possible to merge this rules now?

**Comment by beutlich** [comment]
> 
> 
> @beutlich Possible to merge this rules now?

Do not know what to do this PR since I have not got all approvals.

**Comment by tobolar** [comment]
I have just checked the list of reviewers and they all seem to approve it. But you are right, there are some persons still missing.

**Comment by beutlich** [comment]
OK, I'll care for the conflict (sigh) and merge later on.

**Pull request merged**
